package xjsnark.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class JUnsignedBigIntegerHexConstantString_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("0x[0-9a-fA-F]+(u|U)");
  }
}
