package xjsnark.sortingVerification;

/*Generated by MPS */

import java.util.Comparator;
import java.math.BigInteger;

public class IndexComparator implements Comparator<Integer> {

  private BigInteger[] a;
  public IndexComparator(BigInteger[] array) {
    this.a = array;
  }
  @Override
  public int compare(Integer index1, Integer index2) {
    return a[index1].compareTo(a[index2]);
  }


}
