package xjsnark.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.AbstractLoopStatement_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class BoundedLoop_BehaviorDescriptor extends AbstractLoopStatement_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "xjsnark.structure.BoundedLoop";
  }

}
