package xjsnark.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IOperation_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IBinaryLike_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;
import org.jetbrains.mps.openapi.language.SConcept;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class FieldInverseOp_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IOperation_BehaviorDescriptor, IBinaryLike_BehaviorDescriptor {
  public boolean virtual_canPropagateUnmatchedParenUp_1742226163722653670(SNode __thisNode__, SNode leaf, boolean rightParen) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public SNode virtual_getSyntacticallyLeftSideExpression_1742226163722653708(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_getSyntacticallyRightSideExpression_1742226163722653714(SNode __thisNode__) {
    return null;
  }
  public String virtual_getVariableExpectedName_1213877410087(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_isDotExpressionLegalAsStatement_1239212437413(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isLValue_1213877410080(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_lvalue_1262430001741498364(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_operandCanBeNull_323410281720656291(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public void virtual_setSyntacticallyLeftSideExpression_1742226163722653680(SNode __thisNode__, SNode expr) {
  }
  public void virtual_setSyntacticallyRightSideExpression_1742226163722653694(SNode __thisNode__, SNode expr) {
  }

  @Override
  public String getConceptFqName() {
    return "xjsnark.structure.FieldInverseOp";
  }

}
