package xjsnark.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.BinaryOperation_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class JEqualsExpression_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public int virtual_getPriority_1262430001741497858(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "xjsnark.structure.JEqualsExpression";
  }

}
