package xjsnark.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.IntegerLiteral_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class JIntegerConstant_BehaviorDescriptor extends IntegerLiteral_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public Object virtual_getCompileTimeConstantValue_1238860310638(SNode __thisNode__, SModule module) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "xjsnark.structure.JIntegerConstant";
  }

}
