package xjsnark.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IBinaryLike_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class JNotExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements IBinaryLike_BehaviorDescriptor {
  public boolean virtual_canPropagateUnmatchedParenUp_1742226163722653670(SNode __thisNode__, SNode leaf, boolean rightParen) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public SNode virtual_getSyntacticallyLeftSideExpression_1742226163722653708(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_getSyntacticallyRightSideExpression_1742226163722653714(SNode __thisNode__) {
    return null;
  }
  public void virtual_setSyntacticallyLeftSideExpression_1742226163722653680(SNode __thisNode__, SNode expr) {
  }
  public void virtual_setSyntacticallyRightSideExpression_1742226163722653694(SNode __thisNode__, SNode expr) {
  }

  @Override
  public String getConceptFqName() {
    return "xjsnark.structure.JNotExpression";
  }

}
