package xjsnark.behavior;

/*Generated by MPS */

import java.math.BigInteger;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class JUnsignedBigIntegerHexConstant_BehaviorDescriptor extends JUnsignedBigIntegerLiteral_BehaviorDescriptor {
  public BigInteger virtual_getValue_9006659968701477252(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "xjsnark.structure.JUnsignedBigIntegerHexConstant";
  }

}
