package xjsnark.typesystem;

/*Generated by MPS */


public class KeywordChecker {

  private static String[] reservedPrefix = {"uint_", "F_", "sint_"};
  private static String[] reservedExact = {"bit", "external", "EQ", "AND", "OR", "NOT", "NEQ"};

  public static boolean checkAgainstKeywords(String name) {
    if (name == null || name.equals("")) {
      return true;
    }
    for (String s : reservedPrefix) {
      if (name.startsWith(s)) {
        return false;
      }
    }
    for (String s : reservedExact) {
      if (name.equals(s)) {
        return false;
      }
    }

    return true;
  }


}
